---
application:
  name: "kurdolounge"
  project: "Kurdo Lounge"
  organization: "QoveryCommunity"
  storage:
  - name: "discordbot"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/discordbot"
routers:
- name: "main-kurdolounge"
  routes:
  - application_name: "kurdolounge"
    paths:
    - "/*"
