---
application:
  name: "kurdolounge-bot"
  project: "Kurdo Lounge"
  organization: "QoveryCommunity"
  storage:
  - name: "di"
    size: "30"
    type: "fast_ssd"
    mount_point: "/mnt/di"
databases:
- type: "MYSQL"
  name: "ikbb"
  version: "8.0"
routers:
- name: "main-kurdolounge-bot"
  routes:
  - application_name: "kurdolounge-bot"
    paths:
    - "/*"
